version: "3.8"

services:
  web:
    build:
      context: .
    container_name: django_api
    command: python screenshotapi/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # - .:/screenshotapi/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_server
    ports:
      - "6379:6379"
